"""Automated Airflow DAG generator for migrated pipelines.

Takes a pipeline configuration YAML and produces a production-ready Airflow DAG
with proper error handling, retries, SLA monitoring, and alerting. Supports both
incremental (watermark-based) and full-load patterns.
"""

from __future__ import annotations

import logging
import textwrap
from datetime import datetime
from pathlib import Path
from typing import Optional

from src.config import LoadStrategy, PipelineConfig, TargetFormat

logger = logging.getLogger(__name__)


class DagGenerator:
    """Generates production-ready Airflow DAG files from pipeline configs."""

    TEMPLATE_VERSION = "2.1.0"

    def __init__(self, dag_template: Optional[str] = None):
        self.dag_template = dag_template

    def generate(self, config_path: str | Path, output_dir: str | Path = "dags/") -> str:
        config = PipelineConfig.from_yaml(config_path)
        return self.generate_from_config(config, output_dir)

    def generate_from_config(self, config: PipelineConfig, output_dir: str | Path = "dags/") -> str:
        dag_id = self._build_dag_id(config)
        dag_code = self._render_dag(config, dag_id)

        output_path = Path(output_dir)
        output_path.mkdir(parents=True, exist_ok=True)

        dag_file = output_path / f"{dag_id}.py"
        dag_file.write_text(dag_code)

        logger.info(f"Generated DAG: {dag_file} (template v{self.TEMPLATE_VERSION})")
        return str(dag_file)

    def render_dag_code(self, config: PipelineConfig) -> str:
        dag_id = self._build_dag_id(config)
        return self._render_dag(config, dag_id)

    def _build_dag_id(self, config: PipelineConfig) -> str:
        clean_name = config.source.table.replace(".", "_").replace("-", "_")
        return f"migrate_{clean_name}_dag"

    def _render_dag(self, config: PipelineConfig, dag_id: str) -> str:
        imports = self._render_imports(config)
        default_args = self._render_default_args(config)
        dag_definition = self._render_dag_definition(config, dag_id)
        tasks = self._render_tasks(config)
        dependencies = self._render_task_dependencies(config)

        generated_at = datetime.utcnow().isoformat()

        return f'''"""Auto-generated Airflow DAG for pipeline: {config.pipeline_name}

Generated by: Spark Migration Framework v{self.TEMPLATE_VERSION}
Generated at: {generated_at}
Pipeline ID: {config.pipeline_id}
Source: {config.source.database}.{config.source.table}
Target: {config.target.database}.{config.target.table}
"""

{imports}

{default_args}

{dag_definition}

{tasks}

{dependencies}
'''

    def _render_imports(self, config: PipelineConfig) -> str:
        imports = [
            "from datetime import datetime, timedelta",
            "",
            "from airflow import DAG",
            "from airflow.operators.python import PythonOperator",
            "from airflow.operators.dummy import DummyOperator",
            "from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator",
            "from airflow.sensors.external_task import ExternalTaskSensor",
            "from airflow.utils.trigger_rule import TriggerRule",
        ]

        if config.schedule.slack_channel:
            imports.append(
                "from airflow.providers.slack.operators.slack_webhook import SlackWebhookOperator"
            )

        if config.schedule.alert_emails:
            imports.append("from airflow.operators.email import EmailOperator")

        return "\n".join(imports)

    def _render_default_args(self, config: PipelineConfig) -> str:
        emails = config.schedule.alert_emails
        email_list = ", ".join(f'"{e}"' for e in emails) if emails else ""

        return f'''
default_args = {{
    "owner": "{config.owner}",
    "depends_on_past": False,
    "email": [{email_list}],
    "email_on_failure": {bool(emails)},
    "email_on_retry": False,
    "retries": {config.schedule.retries},
    "retry_delay": timedelta(minutes={config.schedule.retry_delay_minutes}),
    "retry_exponential_backoff": True,
    "max_retry_delay": timedelta(minutes=60),
    "execution_timeout": timedelta(hours=4),
}}'''

    def _render_dag_definition(self, config: PipelineConfig, dag_id: str) -> str:
        tags_str = ", ".join(f'"{t}"' for t in config.tags + ["migration", "auto-generated"])
        sla = config.schedule.sla_minutes

        return f'''
def sla_miss_callback(dag, task_list, blocking_task_list, slas, blocking_tis):
    task_names = [t.task_id for t in task_list]
    msg = f"SLA MISS: {{dag.dag_id}} - Tasks: {{task_names}}"
    print(msg)


with DAG(
    dag_id="{dag_id}",
    default_args=default_args,
    description="{config.description or config.pipeline_name}",
    schedule_interval="{config.schedule.cron_expression}",
    start_date=datetime({self._parse_date(config.schedule.start_date)}),
    catchup=False,
    max_active_runs=1,
    tags=[{tags_str}],
    sla_miss_callback=sla_miss_callback,
) as dag:'''

    def _render_tasks(self, config: PipelineConfig) -> str:
        tasks = []
        tasks.append(self._render_start_task())
        tasks.append(self._render_schema_validation_task(config))

        if config.load_strategy == LoadStrategy.INCREMENTAL:
            tasks.append(self._render_incremental_load_task(config))
        elif config.load_strategy == LoadStrategy.CDC:
            tasks.append(self._render_cdc_load_task(config))
        else:
            tasks.append(self._render_full_load_task(config))

        tasks.append(self._render_quality_check_task(config))
        tasks.append(self._render_end_task())

        if config.schedule.slack_channel:
            tasks.append(self._render_slack_alert_task(config))

        return "\n".join(tasks)

    def _render_start_task(self) -> str:
        return '    start = DummyOperator(task_id="start")'

    def _render_end_task(self) -> str:
        return '''    end = DummyOperator(
        task_id="end",
        trigger_rule=TriggerRule.ALL_SUCCESS,
    )'''

    def _render_schema_validation_task(self, config: PipelineConfig) -> str:
        source_table = f"{config.source.database}.{config.source.table}"
        target_table = f"{config.target.database}.{config.target.table}"

        return f'''    validate_schema = SparkSubmitOperator(
        task_id="validate_schema",
        application="/opt/spark/jobs/schema_validator.py",
        application_args=[
            "--source-table", "{source_table}",
            "--target-table", "{target_table}",
            "--fail-on-error", "true",
        ],
        conf={{
            "spark.executor.memory": "4g",
        }},
        name="schema_validation_{config.source.table}",
    )'''

    def _render_full_load_task(self, config: PipelineConfig) -> str:
        source_table = f"{config.source.database}.{config.source.table}"
        target_path = config.target.path or f"s3://lakehouse/{config.target.database}/{config.target.table}"

        return f'''    migrate_data = SparkSubmitOperator(
        task_id="migrate_data_full",
        application="/opt/spark/jobs/pipeline_migrator.py",
        application_args=[
            "--source-table", "{source_table}",
            "--target-path", "{target_path}",
            "--target-format", "{config.target.format.value}",
            "--write-mode", "overwrite",
            "--pipeline-id", "{config.pipeline_id}",
        ],
        conf={{
            "spark.sql.shuffle.partitions": "200",
            "spark.executor.memory": "8g",
            "spark.executor.cores": "4",
        }},
        name="full_load_{config.source.table}",
    )'''

    def _render_incremental_load_task(self, config: PipelineConfig) -> str:
        source_table = f"{config.source.database}.{config.source.table}"
        target_path = config.target.path or f"s3://lakehouse/{config.target.database}/{config.target.table}"
        watermark = config.source.watermark_column or "updated_at"

        return f'''    migrate_data = SparkSubmitOperator(
        task_id="migrate_data_incremental",
        application="/opt/spark/jobs/pipeline_migrator.py",
        application_args=[
            "--source-table", "{source_table}",
            "--target-path", "{target_path}",
            "--target-format", "{config.target.format.value}",
            "--write-mode", "append",
            "--load-strategy", "incremental",
            "--watermark-column", "{watermark}",
            "--pipeline-id", "{config.pipeline_id}",
        ],
        conf={{
            "spark.sql.shuffle.partitions": "100",
            "spark.executor.memory": "8g",
            "spark.sql.adaptive.enabled": "true",
        }},
        name="incremental_load_{config.source.table}",
    )'''

    def _render_cdc_load_task(self, config: PipelineConfig) -> str:
        source_table = f"{config.source.database}.{config.source.table}"
        target_path = config.target.path or f"s3://lakehouse/{config.target.database}/{config.target.table}"

        return f'''    migrate_data = SparkSubmitOperator(
        task_id="migrate_data_cdc",
        application="/opt/spark/jobs/pipeline_migrator.py",
        application_args=[
            "--source-table", "{source_table}",
            "--target-path", "{target_path}",
            "--target-format", "{config.target.format.value}",
            "--write-mode", "merge",
            "--load-strategy", "cdc",
            "--pipeline-id", "{config.pipeline_id}",
        ],
        conf={{
            "spark.sql.shuffle.partitions": "200",
            "spark.executor.memory": "16g",
        }},
        name="cdc_merge_{config.source.table}",
    )'''

    def _render_quality_check_task(self, config: PipelineConfig) -> str:
        source_table = f"{config.source.database}.{config.source.table}"
        target_table = f"{config.target.database}.{config.target.table}"
        tolerance = config.quality.row_count_tolerance_pct

        return f'''    quality_check = SparkSubmitOperator(
        task_id="data_quality_check",
        application="/opt/spark/jobs/quality_validator.py",
        application_args=[
            "--source-table", "{source_table}",
            "--target-table", "{target_table}",
            "--row-count-tolerance", "{tolerance}",
            "--validate-checksums", "{str(config.quality.validate_checksums).lower()}",
        ],
        name="quality_check_{config.source.table}",
    )'''

    def _render_slack_alert_task(self, config: PipelineConfig) -> str:
        return f'''    alert_on_failure = SlackWebhookOperator(
        task_id="alert_on_failure",
        slack_webhook_conn_id="slack_data_alerts",
        message=":red_circle: Migration FAILED: {config.pipeline_name}",
        channel="{config.schedule.slack_channel}",
        trigger_rule=TriggerRule.ONE_FAILED,
    )'''

    def _render_task_dependencies(self, config: PipelineConfig) -> str:
        deps = [
            "",
            "    # Task dependencies",
            "    start >> validate_schema >> migrate_data >> quality_check >> end",
        ]

        if config.schedule.slack_channel:
            deps.append("    [validate_schema, migrate_data, quality_check] >> alert_on_failure")

        return "\n".join(deps)

    @staticmethod
    def _parse_date(date_str: str) -> str:
        parts = date_str.split("-")
        return f"{parts[0]}, {int(parts[1])}, {int(parts[2])}"
